from .admin_views import *
from .doctor_views import *
from .patient_views import *
from .appointment_views import *
from .authentication_views import *
from .common_views import *
from .feature_views import *
from .report_views import *
from .misc_views import *
