# Generated by Django 5.1.5 on 2025-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0019_appointment_appointment_day_doctor_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
                null=True,
            ),
        ),
    ]
