# Generated by Django 5.1.5 on 2025-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0020_patient_dob_patient_is_emergency_alter_doctor_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_discharged",
            field=models.BooleanField(default=False),
        ),
    ]
