# Generated by Django 5.1.5 on 2025-03-08 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0022_userhealth_activity_level_userhealth_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailability",
            name="date_available",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardio"),
                    ("Dermatologists", "Derma"),
                    ("Allergists", "Allergy"),
                    ("General Surgery", "Gen Surg"),
                    ("Pediatricians", "Pedia"),
                    ("Orthopedic Surgeons", "Ortho"),
                    ("Neurologists", "Neuro"),
                    ("Psychiatrists", "Psych"),
                    ("Gynecologists", "Gynae"),
                    ("Endocrinologists", "Endo"),
                ],
                default="Cardiologist",
                max_length=50,
            ),
        ),
    ]
