# Generated by Django 5.1.5 on 2025-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0023_doctoravailability_date_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointmentDate",
            field=models.DateField(),
        ),
    ]
